# -*- coding: utf-8 -*-
"""Depth_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10vJvJokTpG4W2Dno_Ewir-qmNeP0gADw
"""

!pip install torch torchvision torchaudio
!pip install opencv-python pillow matplotlib numpy tqdm
!pip install scikit-image  # for SSIM

# Download Middlebury Stereo Dataset (Example: 'Set 1')
!wget https://vision.middlebury.edu/stereo/data/scenes2021/zip/all.zip
!unzip all.zip -d dataset_folder_new  # Unzip to a specified folder



import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

def load_calibration(calib_file):
  with open(calib_file, 'r') as f:
    lines = f.readlines()

  cam0 = cam1 = None
  baseline = None

  for line in lines:
        if line.startswith('cam0='):
            # Extract and reshape cam0
            cam0_data = line.split('=')[1].strip().strip('[]').replace(';', '').split()
            cam0 = np.array([float(x) for x in cam0_data]).reshape(3, 3)
        elif line.startswith('cam1='):
            # Extract and reshape cam1
            cam1_data = line.split('=')[1].strip().strip('[]').replace(';', '').split()
            cam1 = np.array([float(x) for x in cam1_data]).reshape(3, 3)
        elif line.startswith('baseline='):
            # Extract baseline and convert to float
            baseline_value = line.split('=')[1].strip()  # Get the right side of the '='
            baseline = float(baseline_value)

  return cam0, cam1, baseline

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/JiaRenChang/PSMNet.git
# %cd PSMNet

!pip install gdown
!gdown --id 1p4eJ2xDzvQxaqB20A_MmSP9-KORBX1pZ -O /content/PSMNet/pretrained_model_KITTI2012.tar

import torch
from models.stackhourglass import PSMNet
from collections import OrderedDict

# Initialize model
maxdisp = 192
model = PSMNet(maxdisp=maxdisp)

# Load checkpoint on GPU
checkpoint = torch.load('/content/PSMNet/pretrained_model_KITTI2012.tar')
state_dict = checkpoint['state_dict']

# Remove 'module.' prefix if it exists in checkpoint
new_state_dict = OrderedDict()
for k, v in state_dict.items():
    name = k.replace('module.', '')  # remove 'module.' if present
    new_state_dict[name] = v

model.load_state_dict(new_state_dict)

# Now wrap in DataParallel and move to GPU
model = torch.nn.DataParallel(model).cuda()
model.eval()

print("PSMNet loaded successfully on GPU!")

!pip install torch torchvision torchaudio
!pip install opencv-python pillow matplotlib numpy tqdm

!ls

def compute_disparity_noraml(left_image, right_image):
    stereo = cv2.StereoBM_create(numDisparities=128, blockSize=21)
    disparity = stereo.compute(left_image, right_image).astype(np.float32)
    return disparity

def smooth_disparity(disparity):
    return cv2.medianBlur(disparity, 5)

import torch.nn.functional as F

def compute_disparity(left_image, right_image, model, max_disp=192):
    model.eval()

    # Convert BGR → RGB
    left_image = cv2.cvtColor(left_image, cv2.COLOR_BGR2RGB)
    right_image = cv2.cvtColor(right_image, cv2.COLOR_BGR2RGB)

    # Preprocess
    preprocess = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225])
    ])
    left_tensor = preprocess(left_image).unsqueeze(0)
    right_tensor = preprocess(right_image).unsqueeze(0)

    # Move to GPU
    left_tensor = left_tensor.cuda()
    right_tensor = right_tensor.cuda()

    # Get original height and width
    _, _, h, w = left_tensor.shape

    # Compute padding to make divisible by 16
    pad_h = (16 - h % 16) if h % 16 != 0 else 0
    pad_w = (16 - w % 16) if w % 16 != 0 else 0

    # Pad (left, right, top, bottom)
    left_tensor = F.pad(left_tensor, (0, pad_w, 0, pad_h))
    right_tensor = F.pad(right_tensor, (0, pad_w, 0, pad_h))

    with torch.no_grad():
        disp = model(left_tensor, right_tensor)
        disp = torch.squeeze(disp).cpu().numpy()

    # Crop disparity map back to original size
    disp = disp[:h, :w]

    disp = np.clip(disp, 0, max_disp)
    return disp

def disparity_to_depth(disparity, baseline, focal_length):
  disparity = np.where(disparity == 0, 0.01, disparity)
  depth = baseline * focal_length / disparity
  return depth

def normalize_map(map_here):
    """Normalize input map to the range [0, 1]."""
    min_val, max_val = map_here.min(), map_here.max()
    return (map_here - min_val) / (max_val - min_val)

from skimage.metrics import structural_similarity as ssim
def performance_metrics(depth_map, ground_truth):
  print(f"Depth map range: {depth_map.min()} to {depth_map.max()}")
  print(f"Ground truth range: {ground_truth.min()} to {ground_truth.max()}")
  # Normalize both depth map and ground truth to [0, 1]
  depth_map_norm = normalize_map(depth_map)
  ground_truth_norm = normalize_map(ground_truth)

  # Print normalized ranges
  print(f"Normalized Depth map range: {depth_map_norm.min()} to {depth_map_norm.max()}")
  print(f"Normalized Ground truth range: {ground_truth_norm.min()} to {ground_truth_norm.max()}")

  mse = np.mean((depth_map_norm - ground_truth_norm) ** 2)
  ssim_index = ssim(depth_map_norm, ground_truth_norm, data_range=1.0)
  return mse, ssim_index

from google.colab.patches import cv2_imshow
def process_stereo_images_normal(left_image_path, right_image_path, calib_file, ground_truth_path=None):
  cam0, cam1, baseline = load_calibration(calib_file)
  focal_length = cam0[0,0]

  left_image = cv2.imread(left_image_path, cv2.IMREAD_GRAYSCALE)
  right_image = cv2.imread(right_image_path, cv2.IMREAD_GRAYSCALE)


  disparity = compute_disparity(left_image, right_image)

  depth_map = disparity_to_depth(disparity, baseline, focal_length)

  depth_map_normalized = cv2.normalize(depth_map, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

  if ground_truth_path:
    ground_truth = cv2.imread(ground_truth_path, cv2.IMREAD_GRAYSCALE)
    mse, ssim_index = performance_metrics(depth_map, ground_truth)
    print(f"MSE: {mse}, SSIM: {ssim_index}")

  print('Left Image')
  cv2_imshow(left_image)
  print('Right Image')
  cv2_imshow(right_image)
  print('Disparity Map')
  cv2_imshow(disparity)
  print('Depth Map Normalized')
  cv2_imshow(depth_map_normalized)
  cv2.waitKey(0)
  cv2.destroyAllWindows()

import re
import numpy as np

def load_pfm(file_path):
    """
    Load a PFM (Portable Float Map) file and return a numpy array.
    """
    with open(file_path, 'rb') as f:
        header = f.readline().rstrip().decode('utf-8')
        color = header == 'PF'

        # Read width and height
        dim_line = f.readline().decode('utf-8')
        while dim_line.startswith('#'):  # skip comments
            dim_line = f.readline().decode('utf-8')
        width, height = map(int, dim_line.strip().split())

        # Read scale (negative value means little-endian)
        scale = float(f.readline().decode('utf-8').strip())
        endian = '<' if scale < 0 else '>'
        scale = abs(scale)

        # Read pixel data
        data = np.fromfile(f, endian + 'f')
        shape = (height, width, 3) if color else (height, width)
        data = np.reshape(data, shape)
        data = np.flipud(data)  # PFM has origin at bottom-left
        return data

import numpy as np
import time

def compute_d1_error(pred_disp, gt_disp, mask=None):
    """
    Compute D1-all error.

    Args:
        pred_disp: predicted disparity (H x W)
        gt_disp: ground truth disparity (H x W)
        mask: optional boolean mask to consider valid pixels (default: finite & >0)
    Returns:
        d1_all (%), d1_noc (%)
    """
    if mask is None:
        mask = np.isfinite(gt_disp) & (gt_disp > 0)

    # Absolute error
    error = np.abs(pred_disp - gt_disp)

    # D1 condition: error > 3 px OR > 5% of true disparity
    d1_mask = mask & ((error > 3) & (error / gt_disp > 0.05))
    d1_all = 100.0 * np.sum(d1_mask) / np.sum(mask)

    # Non-occluded mask (assuming gt_disp has occlusion info, if not, use mask)
    d1_noc = d1_all  # If no occlusion info, treat same as all

    return d1_all, d1_noc

# ---------- Main stereo processing ----------
from google.colab.patches import cv2_imshow

def process_stereo_images(left_image_path, right_image_path, calib_file, model, ground_truth_path=None):
    cam0, cam1, baseline = load_calibration(calib_file)
    focal_length = cam0[0, 0]

    left_image = cv2.imread(left_image_path, cv2.IMREAD_COLOR)
    right_image = cv2.imread(right_image_path, cv2.IMREAD_COLOR)
    # Measure runtime
    start_time = time.time()
    disparity = compute_disparity(left_image, right_image, model)
    runtime = time.time() - start_time

    # Convert to depth
    depth_map = disparity_to_depth(disparity, baseline, focal_length)
    depth_map_normalized = cv2.normalize(depth_map, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    # Apply color map to depth map
    depth_color_normalized = cv2.applyColorMap(depth_map_normalized, cv2.COLORMAP_PLASMA)



    if ground_truth_path and os.path.exists(ground_truth_path):
        gt_disp = load_pfm(ground_truth_path)

        # Mask invalid pixels
        mask = np.isfinite(gt_disp) & (gt_disp > 0)
        gt_valid = gt_disp[mask]
        pred_valid = disparity[mask]  # Use disparity for D1 metric

        # Normalize safely for SSIM
        gt_norm = (gt_valid - np.min(gt_valid)) / (np.ptp(gt_valid) + 1e-8)
        pred_norm = (pred_valid - np.min(pred_valid)) / (np.ptp(pred_valid) + 1e-8)

        # Metrics
        mse = np.mean((pred_valid - gt_valid)**2)
        ssim_index = ssim(gt_norm, pred_norm, data_range=1.0)
        d1_all, d1_noc = compute_d1_error(disparity, gt_disp, mask=mask)

        print(f"D1-all: {d1_all:.2f}%, D1-noc: {d1_noc:.2f}%")
        print(f"MSE: {mse:.4f}, SSIM: {ssim_index:.4f}, Runtime: {runtime:.3f}s")

    # Show images and maps
    print('Left Image:')
    cv2_imshow(left_image)
    print('Right Image:')
    cv2_imshow(right_image)
    print('Disparity Map:')
    disp_vis = cv2.applyColorMap(cv2.convertScaleAbs(disparity, alpha=255/np.max(disparity)), cv2.COLORMAP_JET)
    cv2_imshow(disp_vis)
    print('Depth Map Normalized:')
    cv2_imshow(depth_color_normalized)

def test_process_images(base_dir, model):
    for scene in os.listdir(base_dir):
        scene_dir = os.path.join(base_dir, scene)
        if os.path.isdir(scene_dir):
            print(f"\nProcessing scene: {scene}")
            calib_file = os.path.join(scene_dir, 'calib.txt')
            left_image_path = os.path.join(scene_dir, 'im0.png')
            right_image_path = os.path.join(scene_dir, 'im1.png')
            ground_truth_path = os.path.join(scene_dir, 'disp0.pfm')

            if os.path.exists(calib_file) and os.path.exists(left_image_path) and os.path.exists(right_image_path):
                process_stereo_images(left_image_path, right_image_path, calib_file, model, ground_truth_path)

def test_process_images_normal(base_dir):
  for scene in os.listdir(base_dir):
    scene_dir = os.path.join(base_dir,scene)
    if os.path.isdir(scene_dir):
      print(f"Processing scene: {scene}")
      calib_file = os.path.join(scene_dir, 'calib.txt')
      left_image_path = os.path.join(scene_dir, 'im0.png')
      right_image_path = os.path.join(scene_dir, 'im1.png')
      ground_truth_path = os.path.join(scene_dir, 'disp0.pfm')
      if os.path.exists(calib_file) and os.path.exists(left_image_path) and os.path.exists(right_image_path):
        print(f"Processing images for scene: {scene}")
        process_stereo_images(left_image_path, right_image_path, calib_file, ground_truth_path)

base_directory = '/content/dataset_folder_new/data/'
test_process_images(base_directory, model)