artifact_location: /home/ubuntu/Documents/THP_CODES/Q1_Object Detection/runs/mlflow/0
creation_time: 1729446549593
experiment_id: '0'
last_update_time: 1729446549593
lifecycle_stage: active
name: Default
